version: "3" 
# Defines which compose version to use
services:
  # Services line define which Docker images to run. In this case, it will be MySQL server and WordPress image.
  db:
    image: mysql:latest
    # image: mysql:5.7 indicates the MySQL database container image from Docker Hub used in this installation.
    restart: always
    container_name: wordpress_db
    environment:
      MYSQL_ROOT_PASSWORD: Pa$$5w0rD
      MYSQL_DATABASE: WordPressDB
      MYSQL_USER: worpress
      MYSQL_PASSWORD: Pa$$5w0rD
      # Previous four lines define the main variables needed for the MySQL container to work: database, database username, database user password, and the MySQL root password.
    volumes:
      - worpress-db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    container_name: wordpress_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: worpress
      PMA_PASSWORD: Pa$$5w0rD
    ports:
      - "8080:80" 
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpress_container
    restart: always
    # Restart line controls the restart mode, meaning if the container stops running for any reason, it will restart the process immediately.
    ports:
      - "8000:80"
      # The previous line defines the port that the WordPress container will use. After successful installation, the full path will look like this: http://localhost:8000
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: worpress
      WORDPRESS_DB_PASSWORD: Pa$$5w0rD
      WORDPRESS_DB_NAME: WordPressDB
# Similar to MySQL image variables, the last four lines define the main variables needed for the WordPress container to work properly with the MySQL container.
    volumes:
      - ./wordpress-data:/var/www/html
volumes:
  worpress-db: